### ISSUE TITLE
Varaaminen ei toimi

### ISSUE THREAD

**Issue by lamtonylam** [AleksiVirkkala/KideAppBot#3]
![image](https://github.com/AleksiVirkkala/KideAppBot/assets/63186670/ae05a146-76c3-42b9-a06f-b5fce2d0782f)

**Comment by AleksiVirkkala** [comment]
Laitoitko botin päälle ennen myynnin alkamista? Ensimmäinen ajatus on, että se olisi käynnistetty liian myöhään

**Comment by lamtonylam** [comment]
Taisin laittaa, aivan, eli botti toimii vain heti kun lipunmyynti alkaa.

**Comment by AleksiVirkkala** [comment]
Se on hyvä laittaa hieman ennen myynnin alkamista, vaikka minuutin etukäteen. Botti odottelee sitten h-hetkeä kun lipunmyynti alkaa ja aloittaa silloin työnsä. Nykyään liput menee tosi nopeasti, todennäköisesti koska bottaajia ja botteja on kasvavissa määrin. Sen vuoksi veikkaisin, että jos käytön aloittaa kun myynti on alkanut, niin on jo liian myöhäistä.

Voi olla hyvä kokeilla toimivuutta myös toiselle tapahtumalle (vaikket olisi siihen menossakaan) niin saat selkeämmän kuvan miten se toimii. Botti kuitenkin varaa vain liput koriin, niin voit poistaa ne sitten testaamisen jälkeen korista.

**Comment by AleksiVirkkala** [comment]
Tarkennuksena siis vielä, että botin pitäisi toimia vaikka lipunmyynti on alkanut. Tässä tapauksessa vaikuttaa tosin, että liput ehtivät loppua ennen kuin botti sai niitä.

**Comment by karvainenkorva** [comment]
Saan saman ilmoituksen joka kerta. Koitin tänään ostaa lippua tapahtumaan asettamalla botin noin 30 min ennen myyntiä, ja sain saman ilmoituksen kuin AP, vaikka lippuja on vielä tälläkin hetkellä myynnissä. Lisäksi koitin useampaan tapahtumaan ostaa lippua, mitkä on jo pidempään ollut myynnissä, niin törmään aina samaan ongelmaan.

Onko merkitystä millä laitteella bottia käyttää? Käytän itse MacBook Air M1, ja seurasin ohjeita tarkkaan.

**Comment by AleksiVirkkala** [comment]
Katsos vaan, ei muuten toimi itselläkään. Kideapp on tainnut tehdä lähiaikoina muutoksia, koska botti toimi vielä viime viikolla. Otan asian työstöön.

Kiitokset teille @lamtonylam ja @karvainenkorva, että toitte asiat tietoon.

**Comment by AleksiVirkkala** [comment]
Voin vahvistaa, että KideApp on lisännyt vihdoin jonkinlaisen menetelmän bottaamisen estämiselle.

Kun varaus tehdään, mukana pitää olla nyt `x-requested-id` header. En tiedä vielä miten sen arvo lasketaan, mutta se vaikuttaa olevan tapahtumakohtainen.

- Vaikka sivun lataa uudestaan, headerin arvo pysyy samana -> Ei olle sessiokohtainen (voi olla kuitenkin käyttäjäkohtainen)
- Toisessa tapahtumassa on puolestaan eri `x-requested-id` ja edellisen tapahtuman id ei toimi toiseen tapahtumaan.

Vaatii lisäselvittelyä

**Comment by AleksiVirkkala** [comment]
Homma korjattu
