### ISSUE TITLE
Reservation issue

### ISSUE THREAD

**Issue by ajounila** [AleksiVirkkala/KideAppBot#6]
Fetching extra ID...
✅
Received extra ID
:
ce7a72a9286a43e3b8d2228f7ce7b456
Parsing input
✅
Parsed pageId
:
850e798c-c9e7-4ade-a342-ea2f0cb3c0f1
🛰️
Fetching page info...
✅
Received response
:
Tipattoman kaatajaiset
Checking response
🎟️
Sales have started, finding ticket variants...
1
:
OLOlaisen lippu/OLO ticket
‣
Availability
:
88 kpl
‣
Max-order
:
20 kpl
2
:
Lippu tapahtumaan/Ticket
‣
Availability
:
91 kpl
‣
Max-order
:
20 kpl
Reserving ticket
Variant
:
OLOlaisen lippu/OLO ticket
‣
inventoryId
:
87597eff-19f9-4207-8421-be087c1c9f8e
‣
Amount
:
20
📨
Sending reservation...
Reserving ticket
Variant
:
Lippu tapahtumaan/Ticket
‣
inventoryId
:
d487b0ca-c08a-4323-8df0-fb55f18b2cc8
‣
Amount
:
20
📨
Sending reservation...
❌
Variant sold out
❌
Variant sold out
❌
Couldn't reserve any tickets
Process finished succesfully
Time elapsed
:
1879 ms

got this issue while trying to buy tickets to events that have already started their sales/ there are available tickets still left. Trying out whether the bot still works before the actual event where I want the tickets. Seems it can find my information and the ticket information, but when trying to reserve the tickets it states they have already been sold out. Any clue what might be the issue?

**Comment by ajounila** [comment]
reproduced the issue with multiple different events which still have tickets available. Tried the bot on both - edge and chrome - but same issue continues. I'm using version 4.6.0 of the bot

**Comment by AleksiVirkkala** [comment]
Kide.app has probably made some changes. I'll take a look into it

**Comment by AleksiVirkkala** [comment]
All right should be fixed. It was indeed a change in Kide.app end. Can you test if it's working?

The version number should be 4.6.1

**Comment by ajounila** [comment]
@AleksiVirkkala bot is working now, thank you :) issue solved with the v4.6.1

**Comment by AleksiVirkkala** [comment]
Great! Note that kide.app may make similar changes again so feel free to notify me if the bot stops working
