### ISSUE TITLE
extra id ongelma

### ISSUE THREAD

**Issue by AKKE1113** [AleksiVirkkala/KideAppBot#7]
![kide ](https://github.com/user-attachments/assets/f5c197bb-a587-45c1-a653-42a55fce3f57)

**Comment by AleksiVirkkala** [comment]
I have identified the root cause. It's due to some changes at Kideapp end. I'll try to find time to fix it as soon as possible

**Comment by AleksiVirkkala** [comment]
Hey. The problem is fixed and bot is running ✅
